#ifndef DAMIAO_APP_PROFILE_H
#define DAMIAO_APP_PROFILE_H

#include <stdint.h>

#if defined(DAMIAO_DM4310)
#define APP_PROFILE_SOFTWARE_VERSION 0x37313035UL
#define APP_PROFILE_FIRMWARE_VERSION_LITERAL 5017
#define APP_PROFILE_FIRMWARE_SUBVERSION 4U
#define APP_PROFILE_FIRMWARE_SUBVERSION_LITERAL 4
#elif defined(DAMIAO_DM8009)
#define APP_PROFILE_SOFTWARE_VERSION 0x37383137UL
#define APP_PROFILE_FIRMWARE_VERSION_LITERAL 7318
#define APP_PROFILE_FIRMWARE_SUBVERSION 4U
#define APP_PROFILE_FIRMWARE_SUBVERSION_LITERAL 4
#else
#error "Define DAMIAO_DM4310 or DAMIAO_DM8009"
#endif

#endif
