#ifndef HC32F4XX_CONF_H
#define HC32F4XX_CONF_H

/* Enable only DDL modules that are linked by a source firmware target. */
#define LL_ICG_ENABLE          (DDL_ON)
#define LL_UTILITY_ENABLE      (DDL_ON)
#define LL_PRINT_ENABLE        (DDL_OFF)
#define LL_ADC_ENABLE          (DDL_OFF)
#define LL_AES_ENABLE          (DDL_OFF)
#define LL_AOS_ENABLE          (DDL_OFF)
#define LL_CLK_ENABLE          (DDL_OFF)
#define LL_CMP_ENABLE          (DDL_OFF)
#define LL_CRC_ENABLE          (DDL_OFF)
#define LL_CTC_ENABLE          (DDL_OFF)
#define LL_DAC_ENABLE          (DDL_OFF)
#define LL_DBGC_ENABLE         (DDL_OFF)
#define LL_DCU_ENABLE          (DDL_OFF)
#define LL_DMA_ENABLE          (DDL_OFF)
#define LL_EFM_ENABLE          (DDL_ON)
#define LL_EMB_ENABLE          (DDL_OFF)
#define LL_EVENT_PORT_ENABLE   (DDL_OFF)
#define LL_FCG_ENABLE          (DDL_OFF)
#define LL_FCM_ENABLE          (DDL_OFF)
#define LL_GPIO_ENABLE         (DDL_OFF)
#define LL_HASH_ENABLE         (DDL_OFF)
#define LL_I2C_ENABLE          (DDL_OFF)
#define LL_INTERRUPTS_ENABLE   (DDL_OFF)
#define LL_KEYSCAN_ENABLE      (DDL_OFF)
#define LL_MCAN_ENABLE         (DDL_ON)
#define LL_MPU_ENABLE          (DDL_OFF)
#define LL_PWC_ENABLE          (DDL_OFF)
#define LL_QSPI_ENABLE         (DDL_OFF)
#define LL_RMU_ENABLE          (DDL_OFF)
#define LL_RTC_ENABLE          (DDL_OFF)
#define LL_SMC_ENABLE          (DDL_OFF)
#define LL_SPI_ENABLE          (DDL_OFF)
#define LL_SRAM_ENABLE         (DDL_OFF)
#define LL_SWDT_ENABLE         (DDL_OFF)
#define LL_TMR0_ENABLE         (DDL_OFF)
#define LL_TMR4_ENABLE         (DDL_OFF)
#define LL_TMR6_ENABLE         (DDL_OFF)
#define LL_TMRA_ENABLE         (DDL_OFF)
#define LL_TRNG_ENABLE         (DDL_OFF)
#define LL_USART_ENABLE        (DDL_OFF)
#define LL_WDT_ENABLE          (DDL_OFF)

#define BSP_EV_HC32F4XX       (0U)

#endif
