# DM4310 48 V V6017.04: 48 V fixed-SRAM family.
set(DAMIAO_TARGET_COMPILE_DEFINITIONS
    DAMIAO_MODEL_DM4310_48V=1
    DAMIAO_LAYOUT_SHIFTED_SRAM=1
)
include("${CMAKE_CURRENT_LIST_DIR}/dm_v3_common.cmake")
list(APPEND DAMIAO_TARGET_LINK_OPTIONS
    -Wl,--defsym=DAMIAO_LAYOUT_SHIFTED_SRAM=1
)
