# DM8006 V3 V6317.04 uses the alternate fixed-SRAM layout.
set(DAMIAO_TARGET_COMPILE_DEFINITIONS
    DAMIAO_MODEL_DM8006=1
    DAMIAO_LAYOUT_RELOCATED_SRAM=1
)
include("${CMAKE_CURRENT_LIST_DIR}/dm_v3_common.cmake")
list(APPEND DAMIAO_TARGET_LINK_OPTIONS
    -Wl,--defsym=DAMIAO_LAYOUT_RELOCATED_SRAM=1
)
