#!/usr/bin/env python3
"""Generate absolute linker symbols for the recovered app function map."""

from __future__ import annotations

import argparse
import csv
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--functions", type=Path,
                        default=ROOT / "recovered/raw/app_functions.tsv")
    parser.add_argument("--output", type=Path,
                        default=ROOT / "exact/generated/recovered_symbols.ld")
    args = parser.parse_args()

    with args.functions.open(newline="", encoding="utf-8") as stream:
        rows = list(csv.DictReader(stream, delimiter="\t"))
    counts = Counter(row["name"] for row in rows)
    emitted: set[str] = set()
    lines = [
        "/* Generated by tools/generate_exact_symbols.py; do not hand-edit. */",
        "/* Symbols are even code addresses; Cortex-M executes them as Thumb. */",
        "",
    ]
    for row in rows:
        name = row["name"]
        address = int(row["address"], 16)
        if counts[name] > 1 and name in emitted:
            name = f"{name}_at_{address:08x}"
        emitted.add(row["name"])
        lines.append(f"{name} = 0x{address:08x};")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
